#!/usr/bin/env node

const args = require('yargs').argv;
const Haikunator = require('haikunator');
const cli = require('./src/cli');
const csvql = require('./index');
const path = require('path');

const files = args._;
const haikunator = new Haikunator();

const persist = (args.hasOwnProperty('persist') || args.hasOwnProperty('p')) ?
    path.resolve(
        __dirname,
        'data',
        (typeof args.p !== 'boolean' && args.persist !== 'boolean' ?
        (args.p || args.persist) :
        haikunator.haikunate()) + '.sqlite'
    ) :
    false;
const verbose = args.verbose;

async function main() {
    const instance = await csvql(files, { persist });
    cli(instance);
}

main().catch(err => {
    if(verbose) console.error(err);
    else console.error('Runtime Error: ' + err.message);
    process.exit(1);
});