#!/usr/bin/env node

const args = require('yargs').argv;
const Haikunator = require('haikunator');
const cli = require('./src/cli');
const csvql = require('./index');
const path = require('path');

const files = args._;
const haikunator = new Haikunator();

const persist = (args.hasOwnProperty('persist') || args.hasOwnProperty('p')) ?
    path.resolve(
        __dirname,
        'data',
        (typeof args.p !== 'boolean' && args.persist !== 'boolean' ?
        (args.p || args.persist) :
        haikunator.haikunate()) + '.sqlite'
    ) :
    false;

const from = args.from || args.f ?
    (path.isAbsolute(args.from || args.f) ?
    args.from || args.f :
    path.resolve(__dirname, 'data', args.from || args.f)) :
    null;

const verbose = args.verbose;

async function main() {
    const instance = await csvql(files, { persist, from });

    if(from) {
        console.log('Importing session from: ' + from);
    } else if (persist) {
        console.log('The session will be saved on: ' + persist);
    }

    cli(instance);
}

main().catch(err => {
    if(verbose) console.error(err);
    else console.error('Runtime Error: ' + err.message);
    process.exit(1);
});